name: STORM
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - yacs
  - tensorboardx
  - tensorboard
  - moviepy
  - colorama
  - einops
  - tqdm
  - opencv
  - gym[atari,accept-rom-license]

